In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6],np.int8) #int8 is the datatype

In [3]:
arr

array([1, 2, 3, 4, 5, 6], dtype=int8)

In [4]:
arr[1]

2

In [5]:
arr.shape

(6,)

In [8]:
arr.dtype

dtype('int8')

In [6]:
# conversion of python data structures to numpy array
listarr=np.array([[1,2,4],[5,8,9],[4,5,6]])

In [7]:
listarr

array([[1, 2, 4],
       [5, 8, 9],
       [4, 5, 6]])

In [12]:
listarr.shape

(3, 3)

In [13]:
listarr.size

9

In [14]:
# intrinsic numpy creation
zeros=np.zeros((3,3))

In [15]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
zeros.shape

(3, 3)

In [17]:
rng=np.arange(15) #gives numbers from o to 14

In [18]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
lspace=np.linspace(1,5,12) # gives 12 equally spaced values from 1 to 5

In [20]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [21]:
emp=np.empty((4,6)) #gives empty elements with random values of 4 rows and 6 cols

In [22]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33511290e-306, 6.23058368e-307, 8.45593934e-307],
       [7.56593017e-307, 1.11261027e-306, 1.11261502e-306,
        1.42410839e-306, 7.56597770e-307, 6.23059726e-307],
       [1.42419530e-306, 7.56602523e-307, 1.29061821e-306,
        8.45604120e-307, 8.34424766e-308, 9.45699680e-308],
       [1.11261774e-306, 1.29060871e-306, 8.34424766e-308,
        8.34445138e-308, 1.37959129e-306, 1.02360528e-306]])

In [23]:
emp_like=np.empty_like(lspace) #stores the previos array copy in this array

In [24]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [25]:
ide=np.identity(3) # gives identy matrix

In [26]:
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
arr=np.arange(99)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr=arr.reshape(3,33) #gives reshape of arr as 3x33. only if 3x33=99 if 91 then gives error

In [32]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [35]:
arr=arr.ravel() # makes 1d array again

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [38]:
ar=np.array(x)

In [39]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [40]:
ar.sum(axis=0) # axis=0 gives sum of elementds in row 0,1,2 as list

array([12,  8,  9])

In [41]:
ar.sum(axis=1) #axis=1 gives sum of elements in cols 0,1,2

array([ 6, 15,  8])

In [42]:
ar.T #gives transpose of matrix

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [43]:
 ar.flat #gives iterator

In [44]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [45]:
ar.ndim #gives dimension of the array

2

In [46]:
ar.size

9

In [52]:
one=np.array([1,2,30,4,5])

In [49]:
one.argmax() #gives index of the maximum element

<function ndarray.argmax>

In [50]:
one.argmin()

0

In [53]:
one.argsort() # sorts the array and gives the indexes of the sorted array

array([0, 1, 3, 4, 2], dtype=int64)

In [56]:
ar.argmin() # for a 2d array it first makes it as 1 d array and then gives position of smallest element

8

In [57]:
ar.argmax(axis=0) #gives list of max element in each row

array([2, 1, 1], dtype=int64)

In [58]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [59]:
ar.argsort(axis=0) #sorts the elements based on the x axis

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [60]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [61]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [62]:
ar2=np.array([[1,2,1],[4,0,6],[8,1,0]])

In [63]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [65]:
ar*ar2 #element wise multiplication

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [66]:
np.sqrt(ar) #gives sqrt of each element

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [67]:
ar.sum()

29

In [68]:
ar.max()

7

In [71]:
ar.min()

0

In [72]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [70]:
np.where(ar>5) #gives tuples of position of elements >5

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [73]:
np.count_nonzero(ar)

8

#numpytutorial2

In [75]:
a=np.array([1,2,3])

In [76]:
print(a)

[1 2 3]


In [79]:
b

array([[1. , 2. , 3. , 4. ],
       [1. , 2.4, 5.6, 3.5]])

In [80]:
#get dimension 
a.ndim

1

In [81]:
b.ndim

2

In [82]:
#get shape
a.shape

(3,)

In [83]:
b.shape

(2, 4)

In [84]:
# get the type
a.dtype

dtype('int32')

In [85]:
b.dtype

dtype('float64')

# accesing?changing spwcific elements,rows,colums etc

In [88]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [89]:
# get a specific element
a[1][5]

13

In [90]:
# get specific row
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [92]:
# get specific column
a[:,2]

array([ 3, 10])

In [93]:
a[0,1:6:2] # the 2 is step index which gives result of +2 

array([2, 4, 6])

In [94]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [95]:
a[:,2]=5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [98]:
#3d
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [99]:
# get specific element
b[0,1,1]

4

In [100]:
b[0,1,:]

array([3, 4])

In [103]:
# replace 
b[:,1,:]=[9,9]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [9, 9]]])

# Initialising diff types of arrays

In [108]:
# all 0s
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [110]:
# all 1s
np.ones(5,dtype='int32')

array([1, 1, 1, 1, 1])

In [111]:
#any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [112]:
#FULL_LIKE
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [114]:
#random decimal numbers
np.random.rand(4,2)

array([[0.23553292, 0.30529367],
       [0.97381247, 0.32323898],
       [0.91613569, 0.82042519],
       [0.32894869, 0.72190661]])

In [116]:
#random int values
np.random.randint(10,size=(3,3)) #INPUT IS max value VALUE AND SIZE

array([[9, 9, 2],
       [7, 2, 4],
       [2, 6, 4]])

In [118]:
np.random.randint(7,10,size=(3,3)) 

array([[7, 7, 7],
       [7, 8, 8],
       [9, 9, 8]])

In [121]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [125]:
#repeat array 3 times
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [134]:
p1=np.ones((5,5),dtype='int32')
z=np.zeros((3,3))
z[1,1]=9
p1[1:4,1:4]=z
p1

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

####be careful when copying arrays

In [137]:
a=np.array([1,2,3,4])
b=a
b[0]=100
print(b)
print(a)# a also changed its value

[100   2   3   4]
[100   2   3   4]


In [138]:
a=np.array([1,2,3,4])
b=a.copy() #used to avoid the value changes
b[0]=100
print(b)
print(a)

[100   2   3   4]
[1 2 3 4]


# Math with numpy

In [139]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [140]:
a+2

array([3, 4, 5, 6])

In [141]:
a-2

array([-1,  0,  1,  2])

In [142]:
a*2

array([2, 4, 6, 8])

In [144]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [145]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [146]:
a**2

array([ 1,  4,  9, 16])

In [147]:
# take the sine value
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# linear algebra

In [152]:
a=np.full((2,3),1)
print(a)
b=np.full((3,2),2)
print(b)
#a*B not gonna work
np.matmul(a,b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [153]:
#find determinant
c=np.identity(3)
np.linalg.det(c)

1.0

In [156]:
#statistics
stats=np.array([[1,2,3],[4,5,6]])
np.min(stats)

1

In [157]:
np.max(stats)

6

In [159]:
np.sum(stats)

21

# Reorganising arrays

In [161]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [163]:
before.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [165]:
#vertically stacking matrices
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [166]:
#horizontal stacks
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [172]:
b=np.array([[1,2,3,4],[1.0,2.4,5.6,3.5]])
b.astype('int32')#change datatype

array([[1, 2, 3, 4],
       [1, 2, 5, 3]])

# advanced indexing and boolean mnasking

In [173]:
b>2

array([[False, False,  True,  True],
       [False,  True,  True,  True]])

In [174]:
b[b>2] # grab values >2

array([3. , 4. , 2.4, 5.6, 3.5])

In [175]:
# youcan index a list with numpy
a=np.array([1,2,3,4,5,6,7,8])
a[[1,3,6]] #passing index values as list

array([2, 4, 7])

In [176]:
np.any(b>2,axis=0)

array([False,  True,  True,  True])